services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    restart: always
  aws-cli:
    depends_on:
      - dynamodb-local
    image: amazon/aws-cli
    container_name: aws-cli
    ports: [ "8081:8080" ]
    environment:
      AWS_ACCESS_KEY_ID: 'blank'
      AWS_SECRET_ACCESS_KEY: 'blank'
      AWS_DEFAULT_REGION: "dynamodb-local"
    command:
      "dynamodb create-table \
           --table-name whats-new \
           --attribute-definitions AttributeName=releaseId,AttributeType=N AttributeName=projectId,AttributeType=N \
           --key-schema AttributeName=releaseId,KeyType=HASH AttributeName=projectId,KeyType=RANGE \
           --provisioned-throughput ReadCapacityUnits=10,WriteCapacityUnits=10 \
           --endpoint-url http://dynamodb-local:8000 || true | cat"