spring:
  application:
    name: whats-new-release-summary
  ai:
    openai:
      chat:
        base-url: http://localhost:11434
        options:
          model: llama3.1
      api-key: abc
tracker:
  api:
    baseUrl: https://www.pivotaltracker.com/services/v5
